import json
R = r"C:\Users\nflach\qe-work\ghost-signals-quantum-session"
src = [("Receipt room", R + r"\output\song\melodic_echo_taps_1.json", "f103da4a-5b03-4d23-9d4c-8170ea8e9f46"),
       ("Square lattice 5x4", R + r"\plugin\maps\square_5x4.json", "d8ad2243-89a0-4528-9a03-456ddd440c3b"),
       ("Disordered chain", R + r"\plugin\maps\disordered_chain.json", "ce972e74-99bc-444e-b42e-a55aa537dede")]
out = ["// Generated by plugin/gen_maps.py from retrocausal-echo-v1 tap maps. Do not edit.",
       "// Each tap: (time in sixteenth notes, level, pan -1..1, polarity +1/-1).", "",
       "pub struct TapMap { pub name: &'static str, pub job: &'static str, pub taps: &'static [(f32, f32, f32, f32)] }", "",
       "pub static MAPS: &[TapMap] = &["]
for name, path, job in src:
    t = json.load(open(path, encoding="utf-8"))
    ex = t["extras"]; step = ex["step_ms"]
    taps = ex["tap_map"]["taps"]
    rows = ", ".join(f"({x['time_ms'] / step:.4f}, {x['level']:.5f}, {x['pan']:.4f}, {float(x['polarity']):.1f})" for x in taps)
    out.append(f'    TapMap {{ name: "{name}", job: "{job}", taps: &[{rows}] }},')
    print(name, len(taps), "taps, max", round(max(x["time_ms"] for x in taps) / step, 1), "sixteenths, inverted", sum(1 for x in taps if x["polarity"] < 0))
out.append("];")
import os; os.makedirs(R + r"\plugin\src", exist_ok=True)
open(R + r"\plugin\src\maps.rs", "w", encoding="utf-8").write("\n".join(out) + "\n")
