"""A small software renderer for the Heesch corona as a 3D asset, shaded with Moth's Entanglement Shader.

Geometry: every cell is a hexagonal prism; the tile's ring sets its height (the original tile is the
tallest, each ring one step lower), so the corona becomes a stepped ziggurat and the three bare cells
of the fifth ring are pits. Faces are drawn back to front (painter's algorithm, exact for a height field).

Shading: a direct port of the engine's own GLSL (entanglement_texture.glsl). For each face,
theta = acos|n.v|, the phase coordinate per RGB wavelength is mod(-2*2pi*d*cos(theta)/lambda, 2pi)/2pi,
and the reflectance comes from the engine's R_lut at (phase, theta). The LUT is the quantum part: it was
generated by entanglement-shader-v1 from the interference of stacked conducting layers.
"""
from __future__ import annotations

import math
from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw

WAVELENGTH = np.array([650.0, 530.0, 470.0])
DIRS = [(1, 0), (0, 1), (-1, 1), (-1, 0), (0, -1), (1, -1)]    # edge k faces these neighbours (y down)


def read_hdr(path) -> np.ndarray:
    """Minimal Radiance RGBE (.hdr) reader, new-style RLE. Returns float32 (H, W, 3), row 0 first."""
    b = Path(path).read_bytes()
    i = b.index(b"\n\n") + 2
    j = b.index(b"\n", i)
    dims = b[i:j].split()
    H, W = int(dims[1]), int(dims[3])
    p = j + 1
    out = np.zeros((H, W, 4), np.uint8)
    for y in range(H):
        if b[p] == 2 and b[p + 1] == 2 and W >= 8:
            p += 4
            for c in range(4):
                x = 0
                while x < W:
                    n = b[p]
                    p += 1
                    if n > 128:
                        out[y, x:x + n - 128, c] = b[p]
                        p += 1
                        x += n - 128
                    else:
                        out[y, x:x + n, c] = np.frombuffer(b[p:p + n], np.uint8)
                        p += n
                        x += n
        else:
            out[y] = np.frombuffer(b[p:p + 4 * W], np.uint8).reshape(W, 4)
            p += 4 * W
    e = out[..., 3].astype(np.int32)
    scale = np.where(e > 0, np.ldexp(1.0, e - 136), 0.0)
    return (out[..., :3] * scale[..., None]).astype(np.float32)


class Shader:
    """entanglement-shader-v1's GLSL, vectorised: reflectance RGB for arrays of cos(theta)."""

    def __init__(self, lut_path, thickness=500.0):
        self.lut = read_hdr(lut_path)[..., 0]      # single-channel LUT (the .r the GLSL samples)
        self.thickness = thickness

    def __call__(self, cos_theta: np.ndarray) -> np.ndarray:
        c = np.clip(np.abs(cos_theta), 0, 1)
        theta = np.arccos(c)
        D = -2.0 * 2 * np.pi * self.thickness * c
        s = np.mod(D[:, None] / WAVELENGTH[None, :], 2 * np.pi) / (2 * np.pi)      # (n, 3)
        t = theta / (np.pi / 2)
        H, W = self.lut.shape
        xs = np.clip((s * W).astype(int), 0, W - 1)
        ys = np.clip((t * (H - 1)).astype(int), 0, H - 1)
        return self.lut[ys[:, None], xs]


def build(data, ring_height=1.6, base=9.0):
    """Prism list: (q, r, height, level, tile_index, bare)."""
    cells = []
    for ti, t in enumerate(data["tiles"]):
        h = base - ring_height * t["level"]
        for q, r in t["cells"]:
            cells.append((q, r, h, t["level"], ti, False))
    for q, r in data["uncovered"]:
        cells.append((q, r, -0.6, 5, -1, True))
    return cells


def render(cells, shader, yaw, pitch=0.62, size=(1280, 720), zoom=1.0, ss=2, tint=None, light=(0.4, -0.5, 0.75)):
    W, H = size[0] * ss, size[1] * ss
    S3 = math.sqrt(3)
    pos = {(q, r): (S3 * (q + r / 2), 1.5 * r, h, lvl, ti, bare) for q, r, h, lvl, ti, bare in cells}
    xs = np.array([p[0] for p in pos.values()])
    ys = np.array([p[1] for p in pos.values()])
    cx, cy = xs.mean(), ys.mean()
    cyaw, syaw, cp, sp = math.cos(yaw), math.sin(yaw), math.cos(pitch), math.sin(pitch)
    view = np.array([syaw * cp, -cyaw * cp, sp])        # towards the camera (orthographic)
    L = np.array(light) / np.linalg.norm(light)
    span = max(xs.max() - xs.min(), ys.max() - ys.min())
    k = zoom * 0.62 * min(W, H) / span

    def proj(x, y, z):
        x, y = x - cx, y - cy
        xr = x * cyaw + y * syaw
        yr = -x * syaw + y * cyaw
        return (W / 2 + k * xr, H / 2 + k * (yr * sp - z * cp) + H * 0.06)

    def depth(x, y, z):
        x, y = x - cx, y - cy
        return -(-x * syaw + y * cyaw) * cp - z * sp      # larger = farther from the camera

    # per-tile centroids: tile tops are gently domed, so each tile catches the light as one piece
    tile_c = {}
    for (q, r), (x, y, h, lvl, ti, bare) in pos.items():
        a = tile_c.setdefault(ti, [0.0, 0.0, 0])
        a[0] += x; a[1] += y; a[2] += 1
    tile_c = {ti: (a[0] / a[2], a[1] / a[2]) for ti, a in tile_c.items()}
    cam = np.array([cx, cy, 0.0]) + 1.25 * span * np.array([syaw * cp, -cyaw * cp, sp])
    faces = []                                             # (depth, polygon, normal, level, bare, kind, centre)
    for (q, r), (x, y, h, lvl, ti, bare) in pos.items():
        corners = [(x + math.cos(math.radians(60 * j - 30)), y + math.sin(math.radians(60 * j - 30))) for j in range(6)]
        for e, (dq, dr) in enumerate(DIRS):
            nb = pos.get((q + dq, r + dr))
            nh = nb[2] if nb else -1.0
            if nh >= h:
                continue
            (x1, y1), (x2, y2) = corners[e], corners[(e + 1) % 6]
            n = np.array([(x1 + x2) / 2 - x, (y1 + y2) / 2 - y, 0.0])
            n /= np.linalg.norm(n)
            poly = [proj(x1, y1, h), proj(x2, y2, h), proj(x2, y2, nh), proj(x1, y1, nh)]
            faces.append((depth((x1 + x2) / 2, (y1 + y2) / 2, (h + nh) / 2), poly, n, lvl, bare, "side",
                          ((x1 + x2) / 2, (y1 + y2) / 2, (h + nh) / 2), (q, r)))
        poly = [proj(cx_, cy_, h) for cx_, cy_ in corners]
        tx, ty = tile_c[ti]
        n = np.array([(x - tx) * 0.07, (y - ty) * 0.07, 1.0])
        faces.append((depth(x, y, h) - 0.01, poly, n / np.linalg.norm(n), lvl, bare, "top", (x, y, h), (q, r)))
    faces.sort(key=lambda f: -f[0])
    normals = np.array([f[2] for f in faces])
    # y is down on the grid, so flip the y component of normals into a right-handed frame
    nv = normals * np.array([1, -1, 1])
    centres = np.array([f[6] for f in faces])
    to_cam = cam[None, :] - centres
    to_cam /= np.linalg.norm(to_cam, axis=1, keepdims=True)
    to_cam *= np.array([1, -1, 1])                         # same handedness flip as the normals
    refl = shader((nv * to_cam).sum(axis=1))               # (n, 3) HDR reflectance, per-face view angle
    lam = np.clip(nv @ L, 0, 1)
    img = Image.new("RGB", (W, H), (8, 13, 19))
    d = ImageDraw.Draw(img)
    rings = tint or [(236, 226, 206), (156, 195, 207), (111, 159, 174), (75, 120, 135), (51, 88, 106), (216, 160, 72)]
    for i, (_, poly, _, lvl, bare, kind, _c, _qr) in enumerate(faces):
        if bare:
            col = np.array([255, 70, 45]) * (0.9 if kind == "top" else 0.5)
        else:
            base = np.array(rings[min(lvl, 5)], float)
            film = refl[i] / (refl[i].max() + 1e-6)
            col = base * (0.24 + 0.3 * lam[i]) + 255 * film * 0.8 * min(1.0, refl[i].max()) ** 0.6
        d.polygon(poly, fill=tuple(int(v) for v in np.clip(col, 0, 255)))
        if kind == "top" and not bare:               # seams where the neighbour is another tile
            q_, r_ = faces[i][7]
            for e, (dq, dr) in enumerate(DIRS):
                nb = pos.get((q_ + dq, r_ + dr))
                if nb is None or nb[4] != pos[(q_, r_)][4]:
                    d.line([poly[e], poly[(e + 1) % 6]], fill=(8, 13, 19), width=max(1, ss))
    return img.resize(size, Image.LANCZOS)
